name: CI/CD Pipeline

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '**/*.md'
      - '**/*.cff'

  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/*.cff'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  get-php-versions:
    name: Get PHP Versions (N-2)
    runs-on: ubuntu-latest
    outputs:
      version-matrix: ${{ steps.get-language-versions.outputs.latest-versions }}

    steps:
      - name: Get Required Versions
        uses: ActionsToolbox/get-language-versions-action@446919617fd774095b5dd3ed71c39dd3fd0d8f4f # v0.1.3
        id: get-language-versions
        with:
          language: "php"
          remove-patch-version: true
          max-versions: 3

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Perform ShellCheck Analysis
        env:
          EXCLUDE_FILES: vendor
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/shellcheck/master/pipeline.sh)

  php-lint:
    name: PHP Lint
    needs: get-php-versions
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ${{ fromJson(needs.get-php-versions.outputs.version-matrix) }}

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2.35.5
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Perform PHP Lint Analysis
        env:
          EXCLUDE_FILES: vendor
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/php-lint/master/pipeline.sh)

  cicd-pipeline:
    if: always()
    name: CI/CD Pipeline
    needs:
      - shellcheck
      - php-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Check Job Statuses
        run: .github/scripts/check-jobs.sh '${{ toJson(needs) }}'
